[common]
# FRP 服务器地址 (必填)
server_addr = www.baidu.com
# FRP 服务器端口 (默认为 7000)
server_port = 7000
# 身份验证令牌 (建议配置)
# token = 12345678

[ssh]
# 协议类型 (tcp, udp, http, https, stcp, xtcp)
type = tcp
# 内网服务的 IP 地址 (默认为 127.0.0.1)
local_ip = 127.0.0.1
# 内网服务的端口 (如 SSH 为 22)
local_port = 22
# 在 FRP 服务器上暴露的远程端口
remote_port = 6001
